version: "3"

services:
  next-app:
    container_name: next-app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 256M

  # Add more containers below (nginx, postgres, etc.)

  express:
    container_name: express-api
    build:
      context: ./
      dockerfile: express.Dockerfile
    ports:
      - 8080:8080
